Make .coverage.* files combinations more robust

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -27,4 +27,12 @@ after_success:
     # Ignore codecov failures because we don't want travis to report a
     # failure in the github UI just because the coverage report failed
     # to be published.
-    - if [[ "$COVERAGE" == "true" ]]; then codecov || echo "failed"; fi
+    - |
+      if [[ "$COVERAGE" == "true" ]]; then
+        # running joblib tests with coverage enabled produces empty .coverage.*
+        # files when starting subprocesses. They prevent proper combinations of
+        # .coverage.* files through "coverage combine" (run under the hood by
+        # codecov >= 2.0.13) The next line cleans up empty .coverage.* files
+        find -name '.coverage.*' -size 0 -delete
+        codecov || echo "failed"
+      fi
